apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: myapp_backend
        imagePullPolicy: Never
        ports:
          - containerPort: 4000
        env:
          - name: DATABASE_HOST
            value: "db"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            value: "5253"
          - name: DATABASE_NAME
            value: "task_manager"
          - name: FRONTEND_URL
            value: "http://192.168.49.2:32325" # port "http://34.30.173.133:3000"

---
# GCP
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: backend

# Minikube
#apiVersion: v1
#kind: Service
#metadata:
#  name: backend
#spec:
#  type: NodePort
#  ports:
#    - port: 4000
#      targetPort: 4000
#      nodePort: 32306
#  selector:
#    app: backend
