apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: myapp_backend
        imagePullPolicy: Never
        ports:
          - containerPort: 4000
        env:
          - name: DATABASE_HOST
            value: "db"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            value: "5253"
          - name: DATABASE_NAME
            value: "task_manager"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: backend