version: '3'
services:
  frontend:
    image: myapp_frontend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - backend

  backend:
    image: myapp_backend:latest
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=5253
      - DATABASE_NAME=task_manager
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 5253
      MYSQL_DATABASE: task_manager
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

volumes:
  mysql_data:
