apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: myapp_frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://192.168.49.2:32306"  # port http://34.42.30.190:4000
        
---
# GCP
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend

# Minikube
#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend
#spec:
#  type: NodePort
#  ports:
#    - port: 3000
#      targetPort: 3000
#      nodePort: 32325
#  selector:
#    app: frontend